[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
indicatif = "0.17.5"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
